version: '3'
services:
  app:
    image: log-app:latest
    container_name: log-app
    build:
      context: .
    ports:
      - "8092:8080"
    environment:
      - TZ=Asia/Novosibirsk
    restart: always